Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/LineLength:
  Max: 100

Style/StructInheritance:
  Enabled: false

AllCops:
  Exclude:
    - 'primes_multiplication.gemspec'
